apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: isdialogmote-alerts
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  groups:
    - name: isdialogmote-alerts
      rules:
        - alert: ISDIALOGMOTE IS DOWN
          expr: kube_deployment_status_replicas_available{deployment="isdialogmote"} == 0
          for: 30s
          annotations:
            consequence: Application is unavailable
            action: "Undersøk hvorfor pods er nede og få den kjørende igjen!"
            summary: "Det er ingen pods for app kjørende i namespace og dermed er appen nede"
          labels:
            namespace: teamsykefravr
            severity: danger
        - alert: FAILURES IN CRONJOB FOR JOURNALFORING
          expr: sum(increase(isdialogmote_cronjob_journalforing_fail_count_total{app="isdialogmote"} [1h])) > 0
          for: 5m
          annotations:
            action: "Undersøk hvorfor det feiler i logger og om det er en midlertidig feil eller ikke."
            summary: "{{ $labels.app }} klarer ikke å journalføre en eller flere Varsel."
          labels:
            namespace: teamsykefravr
            severity: danger
        - alert: FAILURES IN CRONJOB FOR PUBLISHING MOTESTATUS-ENDRING
          expr: sum(increase(isdialogmote_cronjob_publish_status_endring_fail_count_total{app="isdialogmote"} [1h])) > 0
          for: 5m
          annotations:
            consequence: Application is unavailable
            action: "Undersøk hvorfor det feiler i logger og om det er en midlertidig feil eller ikke."
            summary: "{{ $labels.app }} klarer ikke å publisere en eller flere DialogmoteStatusEndring."
          labels:
            namespace: teamsykefravr
            severity: danger
