apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isdialogmote
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: { { image } }
  port: 8080
  replicas:
    min: 3
    max: 6
    cpuThresholdPercentage: 70
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  ingresses:
    - "https://isdialogmote.intern.nav.no"
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-1-3840
        databases:
          - name: isdialogmote-db
        diskAutoresize: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: syfomoteoversikt
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: dialogmote-frontend
          namespace: team-esyfo
          cluster: prod-gcp
        - application: esyfo-proxy
          namespace: team-esyfo
          cluster: prod-gcp
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "ereg-services.prod-fss-pub.nais.io"
        - host: "pdl-api.prod-fss-pub.nais.io"
        - host: "dokarkiv.prod-fss-pub.nais.io"
        - host: "www.altinn.no"
      rules:
        - application: digdir-krr-proxy
          namespace: team-rocket
        - application: ispdfgen
        - application: isnarmesteleder
        - application: isoppfolgingstilfelle
        - application: syfobehandlendeenhet
        - application: istilgangskontroll
        - application: isdialogmelding
        - application: arkivporten
          namespace: team-esyfo
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  valkey:
    - instance: cache
      access: readwrite
  tokenx:
    enabled: true
  envFrom:
    - secret: isdialogmote-serviceuser
    - secret: isdialogmote-altinnuser
  kafka:
    pool: nav-prod
  env:
    - name: KTOR_ENV
      value: "production"
    - name: JOURNALFORING_RETRY_ENABLED
      value: "true"
    - name: DOKARKIV_CLIENT_ID
      value: "prod-fss.teamdokumenthandtering.dokarkiv"
    - name: DOKARKIV_URL
      value: "https://dokarkiv.prod-fss-pub.nais.io"
    - name: ISOPPFOLGINGSTILFELLE_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isoppfolgingstilfelle"
    - name: ISOPPFOLGINGSTILFELLE_URL
      value: "http://isoppfolgingstilfelle"
    - name: EREG_URL
      value: "https://ereg-services.prod-fss-pub.nais.io"
    - name: KRR_CLIENT_ID
      value: "prod-gcp.team-rocket.digdir-krr-proxy"
    - name: KRR_URL
      value: "http://digdir-krr-proxy.team-rocket"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "http://syfobehandlendeenhet"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "prod-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_URL
      value: "http://istilgangskontroll"
    - name: NARMESTELEDER_URL
      value: "http://isnarmesteleder"
    - name: NARMESTELEDER_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isnarmesteleder"
    - name: DIALOGMELDING_URL
      value: "http://isdialogmelding"
    - name: DIALOGMELDING_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isdialogmelding"
    - name: ALTINN_WS_URL
      value: "https://www.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc"
    - name: OUTDATED_DIALOGMOTE_CUTOFF
      value: "2025-01-01"
    - name: ALTINN_SENDING_ENABLED
      value: "true"
    - name: ARKIVPORTEN_URL
      value: http://arkivporten
    - name: ARKIVPORTEN_SCOPE
      value: prod-gcp.team-esyfo.arkivporten
    - name: ARKIVPORTEN_SENDING_ENABLED
      value: "false"
