apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isdialogmote
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 70
  startup:
    path: /is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 384Mi
  ingresses:
    - "https://isdialogmote.intern.nav.no"
    - "https://isdialogmote.nav.no"
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: isdialogmote-db
            diskAutoresize: true
  accessPolicy:
    inbound:
      rules:
        - application: syfomoteoversikt
          namespace: teamsykefravr
          cluster: prod-fss
        - application: dialogmote
          namespace: default
          cluster: prod-sbs
    outbound:
      external:
        - host: "kafka-schema-registry.nais.adeo.no"
        - host: "login.microsoftonline.com"
        - host: "syfobehandlendeenhet.prod-fss-pub.nais.io"
        - host: "syfoperson.prod-fss-pub.nais.io"
        - host: "syfo-tilgangskontroll.prod-fss-pub.nais.io"
      rules:
        - application: isdialogmote-redis
        - application: isdialogmotepdfgen
  azure:
    application:
      enabled: true
      tenant: nav.no
      replyURLs:
        - "https://isdialogmote.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  envFrom:
    - configmap: loginservice-idporten
    - secret: isdialogmote-serviceuser
    - secret: isdialogmote-redis-password
  kafka:
    pool: nav-prod
  env:
    - name: KTOR_ENV
      value: "production"
    - name: AADDISCOVERY_URL
      value: "https://login.microsoftonline.com/navno.onmicrosoft.com/.well-known/openid-configuration"
    - name: DOKARKIV_CLIENT_ID
      value: "162b3255-2f72-4399-8f7a-244add9ffaac"
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: KAFKA_SCHEMA_REGISTRY_URL
      value: "kafka-schema-registry.nais.adeo.no"
    - name: REDIS_HOST
      value: "isdialogmote-redis.teamsykefravr.svc.cluster.local"
    - name: LOGINSERVICE_CLIENT_ID
      value: "9b4e07a3-4f4c-4bab-b866-87f62dff480d"
    - name: DIALOGMOTE_ARBEIDSTAKER_URL
      value: "https://tjenester.nav.no/dialogmote"
    - name: DOKARKIV_URL
      value: "https://dokarkiv.prod-fss-pub.nais.io"
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "97815ed7-ee77-4d6c-ab3b-ea86d93750a7"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "https://syfobehandlendeenhet.prod-fss-pub.nais.io"
    - name: SYFOPERSON_CLIENT_ID
      value: "65bd6a4c-e757-487f-9767-619a5307278f"
    - name: SYFOPERSON_URL
      value: "https://syfoperson.prod-fss-pub.nais.io"
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "dfaa2699-7390-4459-9cfc-2e8de64dfaf9"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "https://syfo-tilgangskontroll.prod-fss-pub.nais.io"
    - name: TOGGLE_PUBLISH_STATUS_ENDRING_CRONJOB_ENABLED
      value: "false"
    - name: TOGGLE_JOURNALFORING_CRONJOB_ENABLED
      value: "false"
    - name: TOGGLE_MQ_SENDING_ENABLED
      value: 'false'
    - name: MQGATEWAY_HOSTNAME
      value: "a01apvl269.adeo.no"
    - name: MQGATEWAY_PORT
      value: '1414'
    - name: MQGATEWAY_NAME
      value: "MPLS02"
    - name: MQGATEWAY_CHANNEL_NAME
      value: "P_ISDIALOGMOTE"
    - name: TREDJEPARTSVARSEL_QUEUENAME
      value: "QA.P_VARSELPRODUKSJON.BEST_SRVMLD_M_KONTAKT"
    - name: NARMESTELEDER_URL
      value: "https://narmesteleder.nav.no"
    - name: NARMESTELEDER_CLIENT_ID
      value: "046419dd-8baa-4343-b192-a14d7c260b38"
