apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isdialogmote
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 70
  liveness:
    path: /is_alive
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  readiness:
    path: /is_alive
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  leaderElection: false
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 384Mi
  ingresses:
    - "https://isdialogmote.dev.intern.nav.no"
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: isdialogmote-db
            diskAutoresize: true
  accessPolicy:
    outbound:
      external:
        - host: kafka-schema-registry.nais-q.adeo.no
        - host: "login.microsoftonline.com"
        - host: "modiasyforest.dev-fss-pub.nais.io"
        - host: "syfomoteadmin.dev-fss-pub.nais.io"
        - host: "syfoperson.dev-fss-pub.nais.io"
        - host: "syfo-tilgangskontroll.dev-fss-pub.nais.io"
      rules:
        - application: isdialogmote-redis
        - application: isdialogmotepdfgen
  envFrom:
    - configmap: loginservice-idporten
    - secret: isdialogmote-serviceuser
    - secret: isdialogmote-redis-password
  env:
    - name: KTOR_ENV
      value: production
    - name: AADDISCOVERY_URL
      value: "https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/.well-known/openid-configuration"
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: KAFKA_SCHEMA_REGISTRY_URL
      value: https://kafka-schema-registry.nais-q.adeo.no
    - name: REDIS_HOST
      value: "isdialogmote-redis.teamsykefravr.svc.cluster.local"
    - name: LOGINSERVICE_CLIENT_ID
      value: "38e07d31-659d-4595-939a-f18dce3446c5"
    - name: DIALOGMOTE_ARBEIDSTAKER_URL
      value: "https://tjenester-q1.nav.no/dialogmote"
    - name: MODIASYFOREST_URL
      value: "https://modiasyforest.dev-fss-pub.nais.io"
    - name: SYFOMOTEADMIN_URL
      value: "https://syfomoteadmin.dev-fss-pub.nais.io"
    - name: SYFOPERSON_URL
      value: "https://syfoperson.dev-fss-pub.nais.io"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "https://syfo-tilgangskontroll.dev-fss-pub.nais.io"
