apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isdialogmote
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 384Mi
  ingresses:
    - "https://isdialogmote.intern.dev.nav.no"
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-f1-micro
        databases:
          - name: isdialogmote-db
        diskAutoresize: true
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfomoteoversikt
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: dialogmote-frontend
          namespace: team-esyfo
          cluster: dev-gcp
        - application: esyfo-proxy
          namespace: team-esyfo
          cluster: dev-gcp
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "ereg-services-q1.dev-fss-pub.nais.io"
        - host: "pdl-api.dev-fss-pub.nais.io"
        - host: "dokarkiv.dev-fss-pub.nais.io"
        - host: "tt02.altinn.no"
      rules:
        - application: digdir-krr-proxy
          namespace: team-rocket
        - application: isdialogmote-redis
        - application: ispdfgen
        - application: isnarmesteleder
        - application: isoppfolgingstilfelle
        - application: syfobehandlendeenhet
        - application: istilgangskontroll
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  tokenx:
    enabled: true
  envFrom:
    - secret: isdialogmote-serviceuser
    - secret: isdialogmote-redis-password
    - secret: isdialogmote-altinnuser
  kafka:
    pool: nav-dev
  env:
    - name: KTOR_ENV
      value: production
    - name: REDIS_HOST
      value: "isdialogmote-redis.teamsykefravr.svc.cluster.local"
    - name: DOKARKIV_CLIENT_ID
      value: "dev-fss.teamdokumenthandtering.dokarkiv-q1"
    - name: DOKARKIV_URL
      value: "https://dokarkiv.dev-fss-pub.nais.io"
    - name: ISOPPFOLGINGSTILFELLE_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isoppfolgingstilfelle"
    - name: ISOPPFOLGINGSTILFELLE_URL
      value: "http://isoppfolgingstilfelle"
    - name: EREG_URL
      value: "https://ereg-services-q1.dev-fss-pub.nais.io"
    - name: KRR_CLIENT_ID
      value: "dev-gcp.team-rocket.digdir-krr-proxy"
    - name: KRR_URL
      value: "http://digdir-krr-proxy.team-rocket"
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "http://syfobehandlendeenhet"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "dev-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_URL
      value: "http://istilgangskontroll"
    - name: NARMESTELEDER_URL
      value: "http://isnarmesteleder"
    - name: NARMESTELEDER_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isnarmesteleder"
    - name: ALTINN_WS_URL
      value: "https://tt02.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc"
    - name: OUTDATED_DIALOGMOTE_CUTOFF
      value: "2023-06-01"
    - name: ALTINN_SENDING_ENABLED
      value: "false"
