apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isdialogmote
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 3
    max: 6
    cpuThresholdPercentage: 70
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  ingresses:
    - "https://isdialogmote.intern.nav.no"
    - "https://isdialogmote.nav.no"
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: isdialogmote-db
        diskAutoresize: true
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfomoteoversikt
          namespace: teamsykefravr
          cluster: prod-fss
    outbound:
      external:
        - host: "kafka-schema-registry.nais.adeo.no"
        - host: "login.microsoftonline.com"
        - host: "syfo-tilgangskontroll.prod-fss-pub.nais.io"
        - host: "isproxy.prod-fss-pub.nais.io"
        - host: "pdl-api.prod-fss-pub.nais.io"
        - host: "dokdistfordeling.prod-fss-pub.nais.io"
      rules:
        - application: digdir-krr-proxy
        - application: isdialogmote-redis
        - application: isdialogmotepdfgen
        - application: isnarmesteleder
        - application: syfobehandlendeenhet
  azure:
    application:
      enabled: true
      tenant: nav.no
      replyURLs:
        - "https://isdialogmote.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  envFrom:
    - configmap: loginservice-idporten
    - secret: isdialogmote-serviceuser
    - secret: isdialogmote-redis-password
    - secret: isdialogmote-altinnuser
  kafka:
    pool: nav-prod
  env:
    - name: KTOR_ENV
      value: "production"
    - name: REDIS_HOST
      value: "isdialogmote-redis.teamsykefravr.svc.cluster.local"
    - name: DIALOGMOTE_ARBEIDSTAKER_URL
      value: "https://www.nav.no/syk/dialogmoter/sykmeldt"
    - name: DOKARKIV_CLIENT_ID
      value: "prod-fss.teamdokumenthandtering.dokarkiv"
    - name: DOKARKIV_URL
      value: "https://dokarkiv.prod-fss-pub.nais.io"
    - name: ISOPPFOLGINGSTILFELLE_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isoppfolgingstilfelle"
    - name: ISOPPFOLGINGSTILFELLE_URL
      value: "https://isoppfolgingstilfelle.intern.nav.no"
    - name: ISPROXY_CLIENT_ID
      value: "prod-fss.teamsykefravr.isproxy"
    - name: ISPROXY_URL
      value: "https://isproxy.prod-fss-pub.nais.io"
    - name: KRR_CLIENT_ID
      value: "prod-gcp.team-rocket.digdir-krr-proxy"
    - name: KRR_URL
      value: "https://digdir-krr-proxy.intern.nav.no"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "https://syfobehandlendeenhet.intern.nav.no"
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "prod-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "https://syfo-tilgangskontroll.prod-fss-pub.nais.io"
    - name: MQGATEWAY_HOSTNAME
      value: "mpls02.adeo.no"
    - name: MQGATEWAY_PORT
      value: '1414'
    - name: MQGATEWAY_NAME
      value: "MPLS02"
    - name: MQGATEWAY_CHANNEL_NAME
      value: "P_ISDIALOGMOTE"
    - name: TREDJEPARTSVARSEL_QUEUENAME
      value: "QA.P_VARSELPRODUKSJON.BEST_SRVMLD_M_KONTAKT"
    - name: NARMESTELEDER_URL
      value: "https://isnarmesteleder.intern.nav.no"
    - name: NARMESTELEDER_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isnarmesteleder"
    - name: ALTINN_WS_URL
      value: https://www.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc
    - name: DOKDIST_FORDELING_URL
      value: "https://dokdistfordeling.prod-fss-pub.nais.io"
    - name: DOKDIST_FORDELING_CLIENT_ID
      value: "prod-fss.teamdokumenthandtering.saf"
    - name: ALTINN_NOTIFICATION_ENABLED
      value: "true"
