apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamsykefravr
  namespace: teamsykefravr
  name: isdialogmote-redis
spec:
  image: redis:5-alpine
  port: 6379
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  service:
    port: 6379
    protocol: redis
  accessPolicy:
    inbound:
      rules:
        - application: isdialogmote
