-- ROLLBACK-START
------------------
-- ALTER TABLE MOTEDELTAKER_ARBEIDSTAKER_VARSEL DROP COLUMN IF EXISTS journalpost_id;
---------------
-- ROLLBACK-END

ALTER TABLE MOTEDELTAKER_ARBEIDSTAKER_VARSEL
ADD COLUMN journalpost_id VARCHAR(20);

