ALTER TABLE MOTE_REFERAT
ADD COLUMN brev_bestilling_id VARCHAR(100),
ADD COLUMN brev_bestilt_tidspunkt TIMESTAMP;

ALTER TABLE MOTEDELTAKER_ARBEIDSTAKER_VARSEL
ADD COLUMN brev_bestilling_id VARCHAR(100),
ADD COLUMN brev_bestilt_tidspunkt TIMESTAMP;
