ALTER TABLE MOTE_REFERAT
DROP COLUMN pdf;

ALTER TABLE MOTEDELTAKER_ARBEIDSTAKER_VARSEL
DROP COLUMN pdf;

ALTER TABLE MOTEDELTAKER_ARBEIDSGIVER_VARSEL
DROP COLUMN pdf;

ALTER TABLE MOTEDELTAKER_BEHANDLER_VARSEL
DROP COLUMN pdf;
