UPDATE MOTE_REFERAT
    SET situasjon = '[Teksten er fjernet]',
        konklusjon = '.',
        arbeidstaker_oppgave = '.',
        arbeidsgiver_oppgave = '.',
        veileder_oppgave = null,
        document = '[{"key": null,"type": "HEADER_H1","texts": ["Referat fra dialogmøte"],"title": null},{"key": null,"type": "PARAGRAPH","texts": ["Sendt 6. mai 2022, kl. 11.43"],"title": null},{"key": null,"type": "HEADER_H2","texts": ["[Arbeidstaker]"],"title": null},{"key": null,"type": "PARAGRAPH","texts": ["F.nr. -"],"title": null},{"key": null,"type": "PARAGRAPH","texts": ["Torsdag 5. mai 2022 kl. 14.30"],"title": "Møtetidspunkt"},{"key": null,"type": "PARAGRAPH","texts": ["NAV Arendal, Tyholmen"],"title": "Møtested"},{"key": null,"type": "PARAGRAPH","texts": ["Arbeidstaker: -","Fra NAV: -","Fra arbeidsgiver: -","Behandler: Fastlege -"],"title": "Deltakere i møtet"},{"key": null,"type": "PARAGRAPH","texts": ["[Arbeidsgiver]"],"title": "Arbeidsgiver"},{"key": null,"type": "PARAGRAPH","texts": ["Formålet med dialogmøtet var å oppsummere situasjonen, drøfte mulighetene for å arbeide og legge en plan for tiden framover."],"title": null},{"key": null,"type": "PARAGRAPH","texts": ["Sykdom og diagnose er underlagt taushetsplikt. Derfor er helsen din bare et tema hvis du selv velger å være åpen om den. Av hensyn til personvernet inneholder referatet uansett ikke slike opplysninger. Se artikkel 9, Lov om behandling av personopplysninger."],"title": null},{"key": null,"type": "HEADER_H2","texts": ["Dette skjedde i møtet"],"title": null},{"key": null,"type": "PARAGRAPH","texts": ["."],"title": "Konklusjon"},{"key": null,"type": "PARAGRAPH","texts": ["."],"title": "Din oppgave"},{"key": null,"type": "PARAGRAPH","texts": ["."],"title": "Arbeidsgiverens oppgave"},{"key": null,"type": "PARAGRAPH","texts": ["[Teksten er fjernet]"],"title": "Situasjon og muligheter"},{"key": null,"type": "PARAGRAPH","texts": ["Vennlig hilsen","[Veileder]","NAV"],"title": null}]',
        behandler_oppgave = null
    WHERE uuid = '0ff64e1c-fdfd-4f63-ae47-39287e98dd3c'
