UPDATE MOTE_REFERAT
    SET situasjon = '[Teksten er fjernet]',
        konklusjon = '.',
        arbeidstaker_oppgave = '.',
        arbeidsgiver_oppgave = '.',
        veileder_oppgave = null,
        document = '[{"key": null,"type": "HEADER_H1","texts": ["Referat fra dialogmøte"],"title": null},{"key": null,"type": "PARAGRAPH","texts": ["Sendt 9. januar 2025, kl. 10.40"],"title": null},{"key": null,"type": "HEADER_H2","texts": ["[Arbeidstaker]"],"title": null},{"key": null,"type": "PARAGRAPH","texts": ["F.nr. -"],"title": null},{"key": null,"type": "PARAGRAPH","texts": ["Torsdag 9. januar 2025 kl. 10.00"],"title": "Møtetidspunkt"},{"key": null,"type": "PARAGRAPH","texts": ["Digitalt"],"title": "Møtested"},{"key": null,"type": "PARAGRAPH","texts": ["Arbeidstaker: -","Fra Nav: -","Fra arbeidsgiver: -","Behandler: -"],"title": "Deltakere i møtet"},{"key": null,"type": "PARAGRAPH","texts": ["[Arbeidsgiver]"],"title": "Arbeidsgiver"},{"key": null,"type": "PARAGRAPH","texts": ["Formålet med dialogmøtet var å oppsummere situasjonen, drøfte mulighetene for å arbeide og legge en plan for tiden framover."],"title": null},{"key": null,"type": "PARAGRAPH","texts": ["Sykdom og diagnose er underlagt taushetsplikt. Derfor er helsen din bare et tema hvis du selv velger å være åpen om den. Av hensyn til personvernet inneholder referatet uansett ikke slike opplysninger. Se artikkel 9, Lov om behandling av personopplysninger."],"title": null},{"key": null,"type": "HEADER_H2","texts": ["Dette skjedde i møtet"],"title": null},{"key": null,"type": "PARAGRAPH","texts": ["."],"title": "Konklusjon"},{"key": null,"type": "PARAGRAPH","texts": ["."],"title": "Din oppgave"},{"key": null,"type": "PARAGRAPH","texts": ["."],"title": "Arbeidsgiverens oppgave"},{"key": null,"type": "PARAGRAPH","texts": ["."],"title": "Behandlerens oppgave"},{"key": null,"type": "PARAGRAPH","texts": ["."],"title": "Navs oppgave"},{"key": null,"type": "PARAGRAPH","texts": ["[Teksten er fjernet]"],"title": "Situasjon og muligheter"},{"key": null,"type": "HEADER_H2","texts": ["Dette informerte Nav om i møtet"],"title": null},{"key": "IKKE_BEHOV","type": "PARAGRAPH","texts": ["[Teksten er fjernet]"    ],"title": "Ikke behov for bistand fra Nav nå"},{"key": null,"type": "PARAGRAPH","texts": ["Med vennlig hilsen","[Veileder]","Nav"],"title": null}]',
        behandler_oppgave = null
    WHERE uuid = '43ccddfe-3918-4198-9604-3957882505f9';

UPDATE PDF
    SET pdf = ''::bytea
    WHERE uuid = '844e381c-4617-440e-b179-013c574280be';