name: kafka

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/kafka.yaml'
      - '.nais/kafka/**'

permissions:
  id-token: write

jobs:
  deploy-kafka-dev:
    name: Deploy Kafka topic to NAIS dev-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: deploy statusendring dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/kafka/statusendring.yaml
          VARS: .nais/kafka/dev.json

      - name: deploy dialogmotesvar dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/kafka/dialogmotesvar.yaml
          VARS: .nais/kafka/dev.json


  deploy-kafka-prod:
    name: Deploy Kafka topic to NAIS prod-gcp
    needs: deploy-kafka-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: deploy statusendring prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/kafka/statusendring.yaml
          VARS: .nais/kafka/prod.json

      - name: deploy dialogmotesvar prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/kafka/dialogmotesvar.yaml
          VARS: .nais/kafka/prod.json
